services:
  wfagent:
    image: caroniagent-wf_agent
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      AMQP_URL: amqp://user:pass@rabbitmq:5672/
    depends_on:
      - db
      - web # Hack to avoid DB not being fully available
    networks:
      - default
      - shared_net

  web:
    image: caroniagent-django
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  rabbitmq_data:

networks:
  shared_net:
    external: true